on:
  pull_request:

jobs:
  deploy-to-staging:
    name: deploy-to-staging
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Set environment variables
        run: echo staging

  deploy-to-production:
    name: deploy-to-production
    runs-on: ubuntu-latest
    needs: deploy-to-staging
    environment: production
    steps:
      - name: Set environment variables
        run: echo prod
